# Generated by Django 5.1 on 2025-06-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blogpost_options_remove_blogpost_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_restricted',
            field=models.BooleanField(default=False, verbose_name='Accès restreint (nécessite connexion)'),
        ),
    ]
